### PR TITLE
Use GitHub issues instead of W3C bugzilla.

### PR DESCRIPTION
**Pull request by mounirlamouri**

### CODE REVIEW

**Comment by mounirlamouri** [comment]
@marcoscaceres FYI

**Comment by marcoscaceres** [comment]
thanks!

**Comment by marcoscaceres** [comment]
btw, do you want me to add something like we have for manifest at the top of the doc?

**Comment by mounirlamouri** [comment]
How does that work with the W3C pubrules? Given that we are going for LC, I would prefer to not mess with the pubrules now. We could do after LC for the ED.

**Comment by marcoscaceres** [comment]
I has effect - promise.

**Pull request merged**
