### PR TITLE
Standardize angle orientations counter-clockwise

### LINKED ISSUE #247: Angle not consistently implemented
Over on WebKit, we got a [bug report](https://bugs.webkit.org/show_bug.cgi?id=254863) that `.angle` (and `.type`) are not reported in an interoperable manner.

Using https://krpano.com/ios/bugs/ios164-screen-orientation/ and turning the device clockwise (there are helpful screenshots there too). 

@karlcow did some testing and found:

Firefox Nightly 113 Android 13
screen.orientation.angle: 270
screen.orientation.type: landscape-primary

Chrome Canary 113 Android 13
screen.orientation.angle: 270
screen.orientation.type: landscape-secondary

Safari 16.4 iOS 16.4
screen.orientation.angle: 90
screen.orientation.type: landscape-primary

The spec and the tests agree with Webkit, but we may have a web interop issue at hand. 

Should we change the spec to use counter clockwise values instead? 

@makotokato, wdyt? It would be great if Firefox also reported "landscape-secondary" in this case.

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #247 

The following tasks have been completed:

 * [x] [Modified Web platform tests](https://github.com/web-platform-tests/wpt/pull/39515)

Implementation commitment:

 * [x] [WebKit](https://bugs.webkit.org/show_bug.cgi?id=255388)
 * [X] Chromium  - current behavior 
 * [X] Gecko - current behavior

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/screen-orientation/pull/248.html" title="Last updated on Apr 14, 2023, 1:39 AM UTC (0618c41)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/screen-orientation/248/c6a0731...0618c41.html" title="Last updated on Apr 14, 2023, 1:39 AM UTC (0618c41)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@makotokato, do you have a bug filed for the orientation type on the Gecko side? I can use that as the tracking bug for Gecko above.

**Comment by marcoscaceres** [comment]
Sent PR to update the tests https://github.com/web-platform-tests/wpt/pull/39515

**Comment by marcoscaceres** [comment]
Filed [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=255388) and [sent a patch](https://github.com/WebKit/WebKit/pull/12687).

**Comment by marcoscaceres** [comment]
WebKit patch and tests landed. I'm going to go ahead and merge this, as it aligns all three engines.

**Comment by makotokato** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1829654. I will fix this on 114 or 115.

**Pull request merged**
