### PR TITLE
chore: use GitHub action to validate and auto-publish

### PR DESCRIPTION
**Pull request by sidvishnoi**
Replaces Travis with a GitHub action ([respec-w3c-auto-publish](https://github.com/w3c/respec-w3c-auto-publish)) to validate and auto-publish the spec.

Someone with appropriate permission needs to add `ECHIDNA_TOKEN` in the [GitHub secrets](https://github.com/w3c/screen-orientation/settings/secrets).

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@siusin could you get us a new ECHIDNA_TOKEN?

**Comment by siusin** [comment]
done :)

**Review by siusin — APPROVED** [review]

**Comment by siusin** [comment]
@sidvishnoi what shall we do to get Travis CI report the status of this PR?

**Comment by marcoscaceres** [comment]
@siusin, I think we can remove Travis integration from the settings (or from merging), as this will do the same thing via GitHub actions.

**Comment by sidvishnoi** [comment]
Additionally, we might need to enable Actions in settings, as well as branch protection rules (the action should've run with this PR)

**Comment by sidvishnoi** [comment]
The GitHub action will probably run on next PR once this is merged. Should we merge this? @marcoscaceres

**Comment by sidvishnoi** [comment]
Disabled Travis status check.

**Comment by sidvishnoi** [comment]
Let me see if we can test run the action if I send the PR from same repo, instead from my fork.

**Comment by siusin** [comment]
Hey @sidvishnoi , now you have the admin access, please feel free to change the setting! Is it the plan to apply this change on all the repos using ReSpec?

**Comment by sidvishnoi** [comment]
> now you have the admin access, please feel free to change the setting!

Thanks! I disabled Travis from this repo.

> Is it the plan to apply this change on all the repos using ReSpec?

Only the ones using Travis presently. Will start migration of others once we're happy this action works fine.

**Comment by siusin** [comment]
Thank you @sidvishnoi !

**Pull request closed without merging**
