### PR TITLE
Improve readability regarding active/current orientation lock.

### LINKED ISSUE #46: Rename variables to more clearly indicate what is a list
Elsewhere, @annevk pointed out: 

> "If the active orientation lock is not the current orientation lock" 
> how does this work given that at least current orientation lock is a 
> list? (It would help to rename these variables to more clearly 
> indicate what is a list. That might also help avoid such errors.

### PR DESCRIPTION
**Pull request by mounirlamouri**
This commit is renaming "current orientation lock" as "document's orientation lock" and is clearer about the "active orientation lock" being one document's orientation lock.

It should hopefully fix #46

### CODE REVIEW

**Comment by mounirlamouri** [comment]
@annevk do you prefer that version?

**Comment by mounirlamouri** [comment]
An orientation lock doesn't have to be one value. You can lock to multiple values like "portrait" might lock to "portrait-primary' and "portrait-secondary" but they will be seen as one orientation lock.

I agree that the save isn't great will rewrite that part.

**Comment by mounirlamouri** [comment]
@annevk, please take another look.

**Comment by annevk** [comment]
If a lock can have multiple values, why isn't it a list or a set as I suggested elsewhere?

**Comment by mounirlamouri** [comment]
Anne, I think I applied all your comments (list + "is equivalent"). I'm merging this. Feel free to open another issue if there is something else you want me to change.

**Pull request merged**
