### PR TITLE
Resolving the promise after the change event is fired

### LINKED ISSUE #120: Send events before promise resolve
An annoyance with the orientation lock API, is that the promise resolves before the event is sent.

This makes it hard to default handlers that you don't want to call in certain cases, because if you remove the handler then there is no good place to add it back in, because if you do after the promise gets resolves, it might get called as the event is still pending :-( 

This also means that it makes sense for the unlock to return a promise.

We ran into this in https://github.com/intel/generic-sensor-demos/issues/72

### PR DESCRIPTION
**Pull request by Johanna-hub**
Closes #120

The following tasks have been completed:

 * [x] Confirmed there are no ReSpec/BikeShed errors or warnings.
 * [x] Modified Web platform tests https://github.com/web-platform-tests/wpt/pull/15267

Implementation commitment:

 * [ ] WebKit 
 * [x] [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=930237)
 * [x] [Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1525582)

***
<a href="https://pr-preview.s3.amazonaws.com/Johanna-hub/screen-orientation/pull/147.html" title="Last updated on Feb 19, 2019, 10:38 AM UTC (19e5f68)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/screen-orientation/147/e41f97e...Johanna-hub:19e5f68.html" title="Last updated on Feb 19, 2019, 10:38 AM UTC (19e5f68)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Looks good. I think the gh-pages branch itself needs a tidy tho. I see tidy changes that should be on the gh-pages branch.

**Comment by marcoscaceres** [comment]
@kenchris how do propose we handle this on the Chrome side? This is a breaking change. I think it’s worth doing, but we will need to convince folks (hi @mounirlamouri! 🤗)

**Comment by mounirlamouri** [comment]
Is there a recommended pattern by the TAG or commonly used one from other specifications?

**Comment by kenchris** [comment]
Let me talk with @slightlyoff

**Comment by kenchris** [comment]
Please have a look at https://www.w3.org/2001/tag/doc/promises-guide

**Comment by marcoscaceres** [comment]
@mounirlamouri wrote
> Is there a recommended pattern by the TAG or commonly used one from other specifications?

I was actually thinking of filing a bug on the TAG as this particular situation is not _exactly_ covered by either the API Design Guide or the Promises Guide.  

Regardless, the "pending promise" effectively represents the screen having changed:

```JS
const pendingPromise = new Promise(r => {
  screen.orientation.addEventListener("change", ()=> r(), { once: true });
});
```

**Comment by kenchris** [comment]
> I was actually thinking of filing a bug on the TAG as this particular situation is not _exactly_ covered by either the API Design Guide or the Promises Guide.

Yes, I noticed the same. Please file

**Comment by marcoscaceres** [comment]
@kenchris, the closest I get in the Promises Guide is this section:
https://www.w3.org/2001/tag/doc/promises-guide#one-time-events

> The prototypical example of such an "event" is a loaded indicator: a resource such as an image, font, or even document, could provide a loaded property that is a promise that becomes fulfilled only when the resource has fully loaded (or becomes rejected if there’s an error loading the resource).

The above suggests that the **event occurs**, and, as a result the promise is resolved and rejected based on what the result is.  

> Then, authors can always queue up actions to be executed once the resource is ready by doing resource.loaded.then(onLoaded, onFailure). 

The above follows... 

> This will work even if the resource was loaded already, queueing a microtask to execute onLoaded. This is in contrast to an event model, where if the author is not subscribed at the time the event fires, that information is lost.

... and so on... 

Anyway, will file a bug :)

**Comment by marcoscaceres** [comment]
Filed https://github.com/w3ctag/promises-guide/issues/57

**Comment by marcoscaceres** [comment]
@mounirlamouri, the TAG has kindly updated their [API Design doc](https://github.com/kenchris/design-principles/commit/46ab149c7da5f9d1103144add3b3207a627c8e98
) providing advice around this - thanks @kenchris for making that happen! 

Given the TAG's advice, would you be ok with changing the behavior? @Johanna-hub and I can update the implement on the Gecko side, and provide WPTests.

**Review by marcoscaceres — APPROVED** [review]
LGTM

**Comment by Johanna-hub** [comment]
We now have a test for this https://github.com/web-platform-tests/wpt/pull/15267
@kenchris and anyone else interested, would be great if you could take a look and let us know any comments?

I have also filed a bug on bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1525582

**Comment by mounirlamouri** [comment]
LGTM. I don't know if and when I would update the implementation in Chromium. Though, @Johanna-hub if you want to send a patch, I would happily review :)

**Comment by marcoscaceres** [comment]
@mounirlamouri, sure, we can probably do it. Being new the Blink code base, if you can quickly just point us to the right files, we can go from there.

**Comment by mounirlamouri** [comment]
Actually, I realised that I had in my backlog removing all the Android Jelly Bean support from the screen orientation code. Will probably do both at the same time.

**Comment by marcoscaceres** [comment]
@mounirlamouri, ok cool. We will make sure to have good web platform tests for you at least :)

**Comment by marcoscaceres** [comment]
oh, before I forget, do you want us to file a bug for this specifically on the Chrome side? Or do you have a link to your refactor bug?

**Comment by mounirlamouri** [comment]
I've updated the initial message with the bug number. I have a CL ready that seems to work. Should be in soon.

**Comment by mounirlamouri** [comment]
The change has landed in Blink. Hopefully it will stick. Subtle timing changes like this always worry me :)

**Comment by marcoscaceres** [comment]
Ok, excellent. I’ll make sure the changes happen on the Mozilla side ASAP. Then our implementations can be in sync.

**Review by marcoscaceres — APPROVED** [review]
Ok, let's go with this. We need to fix this up to use task queues, however.

**Comment by marcoscaceres** [comment]
Working on the Gecko patch.

**Comment by marcoscaceres** [comment]
Ok, landed the changes in Gecko too. Fingers crossed it doesn't get backed out.

**Pull request merged**
